packages:
  - pkgs/*
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.22.1+sha512-BCYsx9ezKBWsGGHPlE4WcEjgDX+5pNEnWsCa8Ud8VEiDKbpcjP8XeO8Iap1r3wmiHaQos5xQEKvDF3jblk4mWQ==
loglevel: info
minimumReleaseAgeExclude:
  - "@vitest/expect@4.1.10"
  - "@vitest/mocker@4.1.10"
  - "@vitest/pretty-format@4.1.10"
  - "@vitest/runner@4.1.10"
  - "@vitest/snapshot@4.1.10"
  - "@vitest/spy@4.1.10"
  - "@vitest/utils@4.1.10"
  - vitest@4.1.10
