packages:
  - pkgs/*
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.22.0+sha512-fdLb4xOZfJcyD01rrgm4RT5UR5quezgLY0chciH1oMVq0ogDiAHxlEqJOltS08Rq6WuzBJoV74yysA9T7DkSuA==
loglevel: info
minimumReleaseAgeExclude:
  - "@vitest/expect@4.1.10"
  - "@vitest/mocker@4.1.10"
  - "@vitest/pretty-format@4.1.10"
  - "@vitest/runner@4.1.10"
  - "@vitest/snapshot@4.1.10"
  - "@vitest/spy@4.1.10"
  - "@vitest/utils@4.1.10"
  - vitest@4.1.10
